# Generated by Django 6.0.1 on 2026-01-27 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioLegado',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_usuario', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=100)),
                ('user_permissao_total', models.IntegerField()),
            ],
            options={
                'db_table': 'usuarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistoricoResetPontos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reset', models.DateTimeField(auto_now_add=True, verbose_name='Data do Reset')),
                ('qtd_usuarios_afetados', models.IntegerField(verbose_name='Usuários Zerados')),
                ('total_pontos_removidos', models.IntegerField(verbose_name='Total de Pontos Zerados')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
            ],
            options={
                'verbose_name': 'Histórico de Reset',
                'verbose_name_plural': 'Histórico de Resets',
                'ordering': ['-data_reset'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfil/', verbose_name='Foto de Perfil')),
                ('tipo', models.CharField(choices=[('Administrador', 'Administrador'), ('Usuário Comum', 'Usuário Comum'), ('FILHO', 'Filho / Estudante')], default='Usuário Comum', max_length=20)),
                ('nome_completo', models.CharField(max_length=255)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf', models.CharField(blank=True, max_length=20, null=True)),
                ('cnh', models.CharField(blank=True, max_length=20, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('esta_trabalhando', models.BooleanField(default=False, help_text="Se marcado, exibe o menu 'Jornada' para este usuário.", verbose_name='Módulo Jornada (Trabalho) Ativo?')),
                ('esta_estudando', models.BooleanField(default=False, help_text="Se marcado, exibe o menu 'Estudos' (Planner e Boletim).", verbose_name='Módulo Estudos (Escola/Cursos) Ativo?')),
                ('saldo_pontos', models.IntegerField(default=0, help_text='Pontos acumulados em estudos/tarefas. Pode ser convertido em saldo.', verbose_name='Saldo de Pontos (XP)')),
                ('valor_hora', models.DecimalField(blank=True, decimal_places=2, help_text='Usado para calcular o pagamento no Ponto Eletrônico.', max_digits=10, null=True, verbose_name='Valor da Hora (R$)')),
                ('salario_mensal_bruto', models.DecimalField(blank=True, decimal_places=2, help_text='Apenas informativo.', max_digits=10, null=True, verbose_name='Salário Mensal Bruto (R$)')),
                ('percentual_hora_extra', models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='Percentual Hora Extra (%)')),
                ('ra_numero', models.CharField(blank=True, help_text='Apenas números (Ex: 123456789)', max_length=30, null=True, verbose_name='Número do RA')),
                ('ra_digito', models.CharField(blank=True, help_text='Ex: X, 1, 2', max_length=5, null=True, verbose_name='Dígito RA')),
                ('ra_uf', models.CharField(default='SP', help_text='Estado (Ex: SP)', max_length=2, verbose_name='UF do RA')),
                ('senha_sed', models.CharField(blank=True, help_text='Senha para o robô acessar o boletim automaticamente', max_length=100, null=True, verbose_name='Senha SED (Escola)')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependentes', to=settings.AUTH_USER_MODEL, verbose_name='Responsável (Pai/Mãe)')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
