# Generated by Django 5.2.7 on 2026-02-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='esta_fazendo_curso',
            field=models.BooleanField(default=False, help_text='Marque para quem faz cursos livres/Netflix (Diego, Jéssica, Crianças).', verbose_name='Faz Cursos Extras? (Aba Cursos)'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='esta_estudando',
            field=models.BooleanField(default=False, help_text='Marque para quem frequenta escola regular (Leandro, Manu, etc).', verbose_name='É Estudante Escolar? (Aba Escola)'),
        ),
    ]
