# Generated by Django 5.2.7 on 2026-01-21 10:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('classificacao', models.CharField(choices=[('SAUDAVEL', '✅ Saudável / Equilibrado'), ('MODERADO', '⚠️ Moderado'), ('LIXO', '❌ Lixo / Ultraprocessado')], default='SAUDAVEL', max_length=15)),
                ('calorias', models.IntegerField(default=0, verbose_name='Kcal (aprox)')),
                ('item_estoque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.estoque')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Data')),
                ('tipo', models.CharField(choices=[('CAFE', '☕ Café da Manhã'), ('ALMOCO', '🍽️ Almoço'), ('LANCHE', '🍎 Lanche da Tarde'), ('JANTA', '🍲 Janta'), ('SOBREMESA', '🍰 Sobremesa')], default='ALMOCO', max_length=20)),
                ('descricao_adicional', models.CharField(blank=True, help_text='Ex: Com bastante salada', max_length=255, null=True, verbose_name='Complemento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Obs / Sentimento')),
                ('alimentos', models.ManyToManyField(blank=True, to='alimentacao.alimento', verbose_name='O que comeu?')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Refeição / Diário',
                'verbose_name_plural': 'Refeições',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('item_estoque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.itemcasa')),
                ('refeicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_estoque', to='alimentacao.refeicao')),
            ],
        ),
        migrations.CreateModel(
            name='TabelaNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteinas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Proteínas (g)')),
                ('carboidratos', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Carboidratos (g)')),
                ('gorduras_totais', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Gorduras Totais (g)')),
                ('acucares', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Açúcares (g)')),
                ('sodio', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Sódio (mg)')),
                ('fibras', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Fibras (g)')),
                ('outros_dados', models.JSONField(blank=True, default=dict, verbose_name='Outros / Vitaminas')),
                ('alimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutricao', to='alimentacao.alimento')),
            ],
        ),
    ]
