# Generated by Django 5.2.7 on 2026-01-18 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(choices=[('USUARIO', 'Usuário'), ('PET', 'Pet'), ('CASA', 'Casa')], max_length=10)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supermercado', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('data_compra', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('url_nota', models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='URL / Link da Nota')),
                ('chave_acesso', models.CharField(blank=True, max_length=44, null=True, verbose_name='Chave de Acesso')),
                ('detalhada', models.BooleanField(default=True)),
                ('lancamento_financeiro_criado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoPessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('setor', models.CharField(choices=[('CASA', 'Casa'), ('PET', 'Pets'), ('USUARIO', 'Usuários')], default='USUARIO', max_length=20)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estoquecategoria')),
            ],
            options={
                'unique_together': {('nome', 'setor')},
            },
        ),
        migrations.CreateModel(
            name='EstoqueLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=10)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('item_nome', models.CharField(max_length=255)),
                ('item_setor', models.CharField(max_length=50)),
                ('item_dono', models.CharField(blank=True, max_length=100)),
                ('item_categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('quantidade_antiga', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('quantidade_nova', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimento', models.DateTimeField(auto_now_add=True)),
                ('tipo_movimento', models.CharField(choices=[('CRIACAO', 'Criação'), ('BAIXA', 'Baixa'), ('EDICAO', 'Edição'), ('EXCLUSAO', 'Exclusão'), ('COMPRA', 'Compra')], max_length=20)),
                ('quantidade_movimentada', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('saldo_anterior', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('saldo_atual', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('item_nome_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('item_local_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('estoque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_relacional', to='estoque.estoque')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_movimento'],
            },
        ),
        migrations.CreateModel(
            name='ItemCasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('quantidade', models.DecimalField(decimal_places=3, default=1.0, max_digits=10)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=1.0, max_digits=10)),
                ('estoque_ideal', models.DecimalField(decimal_places=3, default=2.0, max_digits=10)),
                ('validade', models.DateField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estoquecategoria')),
                ('comodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.comodo')),
                ('localizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.localizacao')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unidade')),
            ],
        ),
        migrations.AddField(
            model_name='estoque',
            name='item_casa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.itemcasa'),
        ),
        migrations.CreateModel(
            name='ItemFaltante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, default=1.0, max_digits=10)),
                ('prioridade', models.IntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta')], default=2)),
                ('observacao', models.CharField(blank=True, max_length=200, null=True)),
                ('data_adicionado', models.DateTimeField(auto_now_add=True)),
                ('comodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.comodo')),
                ('item_catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.catalogopessoal')),
                ('localizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.localizacao')),
                ('pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pet')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unidade')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('quantidade', models.DecimalField(decimal_places=3, default=1.0, max_digits=10)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=1.0, max_digits=10)),
                ('estoque_ideal', models.DecimalField(decimal_places=3, default=2.0, max_digits=10)),
                ('validade', models.DateField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estoquecategoria')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.pet')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unidade')),
            ],
        ),
        migrations.AddField(
            model_name='estoque',
            name='item_pet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.itempet'),
        ),
        migrations.CreateModel(
            name='ItemUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('quantidade', models.DecimalField(decimal_places=3, default=1.0, max_digits=10)),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=1.0, max_digits=10)),
                ('estoque_ideal', models.DecimalField(decimal_places=3, default=2.0, max_digits=10)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estoquecategoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_estoque', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='estoque',
            name='item_usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.itemusuario'),
        ),
        migrations.CreateModel(
            name='ListaCompraProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('quantidade', models.DecimalField(decimal_places=3, default=1.0, max_digits=10)),
                ('valor_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adicionado_ao_estoque', models.BooleanField(default=False)),
                ('comodo_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.comodo')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='estoque.listacompra')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unidade')),
            ],
        ),
        migrations.CreateModel(
            name='SimulacaoCenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario_criador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SimulacaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_item', models.CharField(max_length=200)),
                ('preco_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.DecimalField(decimal_places=3, default=1.0, max_digits=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.simulacaocenario')),
            ],
        ),
    ]
