# Generated by Django 6.0.2 on 2026-02-15 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('ispb', models.CharField(blank=True, max_length=12, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='FinancaCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_custo', models.CharField(choices=[('Fixas', 'Fixas'), ('Variadas', 'Variadas')], max_length=10)),
            ],
            options={
                'verbose_name': 'Categoria de Finança',
                'verbose_name_plural': 'Categorias de Finanças',
                'ordering': ['tipo_custo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
                'verbose_name_plural': 'Formas de Pagamento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CenarioFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Nome do Sonho')),
                ('tipo', models.CharField(choices=[('imovel', 'Imóvel / Reforma'), ('veiculo', 'Veículo'), ('viagem', 'Viagem'), ('reserva', 'Reserva de Emergência'), ('outro', 'Outro')], max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total (R$)')),
                ('valor_entrada', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Entrada Disponível (R$)')),
                ('poupanca_mensal_planejada', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Quanto guardar por mês?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cenário Financeiro',
                'verbose_name_plural': 'Cenários Financeiros',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ContaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_shared', models.BooleanField(default=False, verbose_name='Conta da Casa')),
                ('nao_permite_negativo', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contas_financeiras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta Financeira',
                'verbose_name_plural': 'Contas Financeiras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ContaIntegracaoBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco_codigo', models.CharField(choices=[('001', 'Banco do Brasil'), ('033', 'Santander'), ('104', 'Caixa'), ('237', 'Bradesco'), ('341', 'Itaú'), ('260', 'Nubank'), ('077', 'Inter'), ('336', 'C6 Bank'), ('380', 'PicPay'), ('655', 'Votorantim'), ('422', 'Safra'), ('389', 'Banco Mercantil do Brasil'), ('399', 'HSBC (legado)'), ('212', 'Original'), ('290', 'PagBank / PagSeguro'), ('323', 'Mercado Pago'), ('136', 'Unicred'), ('748', 'Sicredi'), ('756', 'Sicoob'), ('999', 'Outro')], max_length=3)),
                ('tipo_conta', models.CharField(choices=[('CORRENTE', 'Conta Corrente'), ('POUPANCA', 'Conta Poupança'), ('CARTAO', 'Cartão'), ('CARTEIRA', 'Carteira'), ('INVEST', 'Investimentos'), ('OUTRO', 'Outro')], default='CORRENTE', max_length=10)),
                ('origem', models.CharField(choices=[('MANUAL', 'Manual (sem integração)'), ('INTEGRADA', 'Integrada (API/OpenFinance/OFX/CSV)')], default='MANUAL', max_length=10)),
                ('provedor', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('SEM', 'Sem integração'), ('PENDENTE', 'Pendente'), ('OK', 'Conectada'), ('ERRO', 'Erro'), ('REVOGADA', 'Revogada')], default='SEM', max_length=10)),
                ('ultima_sincronizacao_em', models.DateTimeField(blank=True, null=True)),
                ('external_account_id', models.CharField(blank=True, max_length=120, null=True)),
                ('external_display_name', models.CharField(blank=True, max_length=120, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integracao', to='financas.contafinanceira')),
            ],
            options={
                'verbose_name': 'Integração Bancária',
                'verbose_name_plural': 'Integrações Bancárias',
                'ordering': ['banco_codigo', 'conta__nome'],
            },
        ),
        migrations.CreateModel(
            name='ContaVinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativa', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='financas.contafinanceira')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_vinculadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vínculo de Conta',
                'verbose_name_plural': 'Vínculos de Contas',
                'ordering': ['usuario__username', 'ordem', 'conta__nome'],
            },
        ),
        migrations.CreateModel(
            name='Financa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Descrição')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(choices=[('Receitas', 'Receitas'), ('Despesas', 'Despesas')], max_length=10)),
                ('conta_tipo', models.CharField(blank=True, choices=[('Fixas', 'Fixas'), ('Variadas', 'Variadas')], max_length=10, null=True)),
                ('origem', models.CharField(choices=[('MANUAL', 'Manual'), ('ROTINA', 'Rotina/Mesada'), ('IMPORT', 'Importação')], default='MANUAL', max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_registro', models.DateField()),
                ('compra_associada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.listacompra')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financas.contafinanceira', verbose_name='Conta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financas.financacategoria')),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financas.formapagamento')),
            ],
            options={
                'verbose_name': 'Lançamento',
                'verbose_name_plural': 'Lançamentos',
                'ordering': ['-data_registro'],
            },
        ),
        migrations.CreateModel(
            name='FinancaComprovante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='comprovantes/%Y/%m/')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('financa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprovantes', to='financas.financa')),
            ],
            options={
                'verbose_name': 'Comprovante',
                'verbose_name_plural': 'Comprovantes',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcelas', models.IntegerField(default=1)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago'), ('Atrasado', 'Atrasado')], default='Pendente', max_length=15)),
                ('financa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes_pagamento', to='financas.financa')),
                ('forma_pagamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financas.formapagamento')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'db_table': 'financas_pagamento',
            },
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.IntegerField(default=1)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago'), ('Atrasado', 'Atrasado')], default='Pendente', max_length=15)),
                ('financa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_parcelas', to='financas.financa')),
                ('pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_vinculadas', to='financas.pagamento')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'db_table': 'financas_parcela',
            },
        ),
        migrations.AddIndex(
            model_name='contafinanceira',
            index=models.Index(fields=['is_shared'], name='financas_co_is_shar_a1fbea_idx'),
        ),
        migrations.AddIndex(
            model_name='contafinanceira',
            index=models.Index(fields=['usuario', 'is_shared'], name='financas_co_usuario_7b5244_idx'),
        ),
        migrations.AddIndex(
            model_name='containtegracaobancaria',
            index=models.Index(fields=['banco_codigo', 'status'], name='financas_co_banco_c_52465a_idx'),
        ),
        migrations.AddIndex(
            model_name='containtegracaobancaria',
            index=models.Index(fields=['provedor', 'status'], name='financas_co_provedo_f6d3e5_idx'),
        ),
        migrations.AddIndex(
            model_name='containtegracaobancaria',
            index=models.Index(fields=['origem', 'status'], name='financas_co_origem_9e17c2_idx'),
        ),
        migrations.AddIndex(
            model_name='contavinculo',
            index=models.Index(fields=['usuario', 'ativa', 'ordem'], name='financas_co_usuario_ee117d_idx'),
        ),
        migrations.AddIndex(
            model_name='contavinculo',
            index=models.Index(fields=['conta', 'ativa'], name='financas_co_conta_i_0d2db4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contavinculo',
            unique_together={('conta', 'usuario')},
        ),
        migrations.AddIndex(
            model_name='financa',
            index=models.Index(fields=['data_registro', 'tipo'], name='financas_fi_data_re_d63710_idx'),
        ),
        migrations.AddIndex(
            model_name='financa',
            index=models.Index(fields=['usuario', 'data_registro'], name='financas_fi_usuario_74eb0f_idx'),
        ),
        migrations.AddIndex(
            model_name='financa',
            index=models.Index(fields=['conta', 'data_registro'], name='financas_fi_conta_i_fd06f3_idx'),
        ),
        migrations.AddIndex(
            model_name='financa',
            index=models.Index(fields=['forma_pagamento'], name='financas_fi_forma_p_b27bee_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['status'], name='financas_pa_status_c5fa5b_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['data_pagamento'], name='financas_pa_data_pa_19efe5_idx'),
        ),
        migrations.AddIndex(
            model_name='parcela',
            index=models.Index(fields=['status'], name='financas_pa_status_c6afba_idx'),
        ),
        migrations.AddIndex(
            model_name='parcela',
            index=models.Index(fields=['data_vencimento'], name='financas_pa_data_ve_b4276e_idx'),
        ),
    ]
