# Generated by Django 6.0.2 on 2026-02-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financacategoria',
            options={'ordering': ['movimento', 'tipo_custo', 'nome'], 'verbose_name': 'Categoria de Finança', 'verbose_name_plural': 'Categorias de Finanças'},
        ),
        migrations.AddField(
            model_name='financacategoria',
            name='movimento',
            field=models.CharField(choices=[('Receitas', 'Receitas'), ('Despesas', 'Despesas')], default='Despesas', max_length=10),
        ),
    ]
