# Generated by Django 6.0.2 on 2026-02-27 11:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_alter_financacategoria_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfrinhoGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Confrinho Inteligente', max_length=120)),
                ('saldo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('percentual_sobra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Confrinho (Global)',
                'verbose_name_plural': 'Confrinho (Global)',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.AddField(
            model_name='containtegracaobancaria',
            name='pix_card_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
