# Generated by Django 6.0.2 on 2026-03-10 22:21

import django.db.models.deletion
import django.utils.timezone
import financas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0003_confrinhoglobal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financacomprovante',
            options={},
        ),
        migrations.RenameField(
            model_name='financacomprovante',
            old_name='data_envio',
            new_name='criado_em',
        ),
        migrations.RemoveField(
            model_name='financacomprovante',
            name='arquivo',
        ),
        migrations.RemoveField(
            model_name='financacomprovante',
            name='descricao',
        ),
        migrations.AddField(
            model_name='financacomprovante',
            name='arquivo_local',
            field=models.FileField(blank=True, null=True, upload_to=financas.models.comprovante_directory_path),
        ),
        migrations.AddField(
            model_name='financacomprovante',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financas.financacategoria'),
        ),
        migrations.AddField(
            model_name='financacomprovante',
            name='data_ref',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financacomprovante',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financacomprovante',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financacomprovante',
            name='mime_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='financacomprovante',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='financacomprovante',
            name='telegram_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financacomprovante',
            name='telegram_file_unique_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financacomprovante',
            name='telegram_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financacomprovante',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
