# Generated by Django 4.2.29 on 2026-04-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('ru', models.CharField(max_length=50, unique=True, verbose_name='Registro de Unidade (RU)')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail do Cliente')),
                ('perfil', models.CharField(choices=[('CEO', 'Administrador / Dono'), ('GERENTE', 'Gerente de Loja'), ('OPERACIONAL', 'Operador de Caixa / Balcão')], default='OPERACIONAL', max_length=20, verbose_name='Nível de Acesso')),
                ('primeiro_acesso', models.BooleanField(default=True, verbose_name='Deve trocar a senha?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Usuário Ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Tem Acesso ao Painel Admin')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
