# Generated by Django 4.2.29 on 2026-04-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariounidade',
            name='cnpj',
            field=models.CharField(default='00000000000000', max_length=18, unique=True, verbose_name='CNPJ da Unidade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuariounidade',
            name='ru',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Registro de Unidade (RU)'),
        ),
    ]
