# Generated by Django 6.0.2 on 2026-03-11 17:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteiraPontos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.PositiveIntegerField(default=0, verbose_name='Saldo Atual de Pontos')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carteira_pontos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoCastigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ocorrencia', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo', models.CharField(max_length=255)),
                ('descricao_detalhada', models.TextField(blank=True)),
                ('gravidade', models.CharField(choices=[('LEVE', 'Leve (Atenção)'), ('MEDIA', 'Média (Advertência)'), ('GRAVE', 'Grave (Disciplina)'), ('GRAVISSIMA', 'Gravíssima (Suspensão)')], default='MEDIA', max_length=20)),
                ('pontos_perdidos', models.IntegerField()),
                ('cumprido', models.BooleanField(default=False, verbose_name='Castigo Finalizado?')),
                ('aplicado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='castigos_aplicados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='castigos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RotinaPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Rotina')),
                ('descricao', models.TextField(blank=True, verbose_name='Diretriz / Instrução')),
                ('pontuacao_base', models.IntegerField(default=10, verbose_name='Pontos Base')),
                ('horario_sugerido', models.TimeField(blank=True, null=True, verbose_name='Horário Sugerido')),
                ('dias_recorrencia', models.CharField(default='ALL', help_text="Ex: 'ALL' ou '0,1,2,3,4'", max_length=50)),
                ('ativa', models.BooleanField(default=True)),
                ('usuarios_padrao', models.ManyToManyField(blank=True, related_name='rotinas_padrao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransacaoPontos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GANHO', 'Ganho (Rotina / Bônus)'), ('PERDA', 'Perda (Castigo / Desobediência)'), ('RESGATE', 'Resgate (Mesada / Prêmio)')], max_length=10)),
                ('pontos', models.PositiveIntegerField()),
                ('descricao', models.CharField(max_length=255)),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='rotinas.carteirapontos')),
            ],
            options={
                'ordering': ['-data_registro'],
            },
        ),
        migrations.CreateModel(
            name='TarefaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_tarefa', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Atribuição')),
                ('prazo_hora', models.TimeField(blank=True, null=True, verbose_name='Prazo Final')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDO', 'Concluído'), ('NAO_FEITO', 'Não Realizado/Falhou')], default='PENDENTE', max_length=20)),
                ('pontos_ganhos', models.IntegerField(default=0, verbose_name='Total de Pontos')),
                ('pontos_extra', models.IntegerField(default=0, verbose_name='Bônus/Penalidade Extra')),
                ('observacao_admin', models.TextField(blank=True, null=True, verbose_name='Feedback do Admin')),
                ('rotina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rotinas.rotinapadrao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'prazo_hora'],
                'unique_together': {('rotina', 'usuario', 'data_tarefa')},
            },
        ),
    ]
