# Generated by Django 6.0.2 on 2026-03-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefadiaria',
            name='prazo_limite',
            field=models.DateTimeField(blank=True, help_text='A hora exata em que a tarefa expira e perde os pontos.', null=True),
        ),
    ]
